from typing import Dict

from .endpoints.bad_path_method_no_2xx_response_available_endpoint import (
    BadPathMethodNo2xxResponseAvailableEndpoint,
)
from .endpoints.bad_path_method_no_summary_endpoint import BadPathMethodNoSummaryEndpoint
from .endpoints.bad_path_parameters_no_schema_attached_endpoint import (
    BadPathParametersNoSchemaAttachedEndpoint,
)
from .endpoints.endpoint_with_description_endpoint import EndpointWithDescriptionEndpoint
from .endpoints.good_path_parameters_query_parameter_as_ref_endpoint import (
    GoodPathParametersQueryParameterAsRefEndpoint,
)
from .endpoints.items_endpoint import ItemsEndpoint
from .endpoints.items_item_id_endpoint import ItemsItemIdEndpoint
from .utils.request_base import RequestBase


class ClientAlpha:
    def __init__(self, base_url: str, default_headers: Dict) -> None:
        """
        API-client generated by [fastapi-client-generator](https://github.com/MichaelPHolstein/fastapi-client-generator).


        NOTE: This is an **alpha version** - Within the first stable version this function will get changed to `Client`


        Args:
            base_url: The base-URL of the API the client will connect with.
            default_headers: A dictionary of HTTP headers automatically included in every request. Additional headers can be provided when calling individual endpoints to override or extend these defaults.
        """

        self._request_base = RequestBase(base_url=base_url, default_headers=default_headers)
        self.items = ItemsEndpoint(request_base=self._request_base)
        self.items_item_id = ItemsItemIdEndpoint(request_base=self._request_base)
        self.endpoint_with_description = EndpointWithDescriptionEndpoint(
            request_base=self._request_base
        )
        self.bad_path_method_no_summary = BadPathMethodNoSummaryEndpoint(
            request_base=self._request_base
        )
        self.bad_path_method_no_2xx_response_available = (
            BadPathMethodNo2xxResponseAvailableEndpoint(request_base=self._request_base)
        )
        self.bad_path_parameters_no_schema_attached = BadPathParametersNoSchemaAttachedEndpoint(
            request_base=self._request_base
        )
        self.good_path_parameters_query_parameter_as_ref = (
            GoodPathParametersQueryParameterAsRefEndpoint(request_base=self._request_base)
        )
