from fastapi_client_generator.interfaces.builder_interface import BuilderInterface
from fastapi_client_generator.shared.config import Config
from fastapi_client_generator.shared.template_enum import TemplateEnum


class UtilsBuilder(BuilderInterface):
    def __init__(self, config: Config):
        super().__init__(config)

    def build(self) -> None:
        """
        Builds the utils for the given client by performing the following steps:

        1. Creating the request base.
        """
        self._create_request_base()

    def _create_request_base(self) -> None:
        """Creates the the base request logic shared by all autogenerated endpoint clients."""
        request_base_template = self._config.jinja_env.get_template(
            name=TemplateEnum.UTIL_REQUEST_BASE.value
        ).render()

        self._config.file_manager.save_python(
            file_path=self._config.root_path / "utils" / "request_base.py",
            code=request_base_template,
        )
