from fastapi_client_generator.builders.schema.schema_builder import SchemaBuilder
from fastapi_client_generator.interfaces.processor_interface import ProcessorInterface
from fastapi_client_generator.shared.config import Config
from fastapi_client_generator.shared.template_enum import TemplateEnum


class SchemaProcessor(ProcessorInterface):
    def __init__(self, config: Config):
        self._config = config

    def run(self):
        """
        Generates the Pydantic schemas for the API-client.

        1. Creates the `/schemas` folder when non existing.
        2. Generates a BaseSchema which is inherited by every autogenerated Pydantic schema.
        3. Generates each schema file.
        """
        self._create_schema_folder()
        self._create_base_schema()
        self._create_schemas()

    def _create_schema_folder(self) -> None:
        """Creates a schema folder if it's not existing yet."""
        action = "Creating schemas folder. (ignored when existing)"
        self._config.log_action(action)

        self._config.file_manager.create_folder(self._config.root_path / "schemas")

    def _create_base_schema(self) -> None:
        """Creates the Pydantic base schema that will be used by all generated pydantic schema's."""
        base_schema_template = self._config.jinja_env.get_template(
            name=TemplateEnum.SCHEMA_BASE_TEMPLATE.value
        ).render()

        self._config.file_manager.save_python(
            file_path=self._config.root_path / "schemas" / "base_schema.py",
            code=base_schema_template,
            overwrite=False,
        )

    def _create_schemas(self) -> None:
        """Collects all schemas from the API-spec and converts them to pydantic schemas."""

        action = "Generating schemas"
        self._config.log_action(action)

        for schema_name, schema_data in self._read_schema_data().items():
            SchemaBuilder(
                config=self._config, schema_name=schema_name, schema_data=schema_data
            ).build()

    def _read_schema_data(self) -> dict:
        """Reads all schemas from the `api-spec.json`."""
        api_spec = self._config.file_manager.load_json(self._config.api_spec_path)
        api_components = dict(api_spec.get("components", {}))
        return dict(api_components.get("schemas", []))
