from typing import List, Tuple

from fastapi_client_generator.builders.utils.utils_builder import UtilsBuilder
from fastapi_client_generator.interfaces.processor_interface import ProcessorInterface
from fastapi_client_generator.shared.config import Config


class UtilsProcessor(ProcessorInterface):
    def __init__(self, config: Config):
        self._config = config
        self._client_base_classes: List[Tuple[str, str]] = []
        self._client_base_imports: List[str] = []

    def run(self):
        """
        Creates the `utils` folder and performs the following steps:

        1. Creates the `/utils` folder when non existing.
        2. Generates a request base that is shared by every autogenerated endpoint.

        """
        self._create_utils_folder()
        self._create_utils()

    def _create_utils_folder(self) -> None:
        """Creates a utils folder if it's not existing yet."""
        action = "Creating utils folder. (ignored when existing)"
        self._config.log_action(action)

        self._config.file_manager.create_folder(self._config.root_path / "utils")

    def _create_utils(self) -> None:
        """Triggers the utils builder."""
        return UtilsBuilder(config=self._config).build()
